language: c

before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq astyle

script:
 - make
 - output=$(make fixstyle | grep formatted); if [[ $output ]]; then while read -r line; do echo -e "\e[00;31m$line\e[00m"; done <<< "$output"; echo -e '\e[00;31mPlease check files formatting using "make fixstyle"\e[00m'; false; fi;
